---
title: Nerdlab
timezone: UTC
collections:
  agenda:
    title: Agenda
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  pictures:
    title: pictures
    output: true
defaults:
- scope:
    path: ''
    type: Agenda
  values:
    when: ''
    link: ''
permalink: pretty
author: Nerdlab
description: Nerdlab is een open collectief van makers. We bouwen installaties en
  machines, organiseren evenementen en veroveren de wereld. Oh, en daarnaast hebben
  een ook fablab in Gent waar iedereen welkom is.
exclude:
- scss
- "*scss"
- Gem*
- Guard*
- "*rb"
- ".sass-cache"
- ".git*"
- config.rb
- "*.md"
- "*.json"
- docroot
- node_modules
- gulpfile.js
- install.sh
- lint.yml
gems:
- jekyll-redirect-from
